server:
  port: 8081
spring:
  application:
    name: socket-server
  session:
    timeout: 84000
    store-type: redis
  redis:
    host: 172.20.10.9
    port: 6379
    password: 123456
    timeout: 1800000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: 1